### ISSUE TITLE
Laggy Acrylic Form

### ISSUE THREAD

**Issue by ffgapple** [arshx86/Themer#1]
When the person try to move the acrylic window with external mouse, its so laggy. But when you try with internal touchpad, its working succesfully. I need a bugfix because, i'm gonna use ur dll in my project :).

**Comment by arshx86** [comment]
> When the person try to move the acrylic window with external mouse, its so laggy. But when you try with internal touchpad, its working succesfully. I need a bugfix because, i'm gonna use ur dll in my project :).

I'm aware of this issue, i don't exactly know why it is happening. You May try to setting **DoubleBuffered** property on form to **true**. I think this is related with Marshal or GC.

**Comment by ffgapple** [comment]
DoubleBuffered is not worked for me, also in Windows 8.1, acrylic theme is going suddenly blue. I'll try to fix this.

**Comment by arshx86** [comment]
> DoubleBuffered is not worked for me, also in Windows 8.1, acrylic theme is going suddenly blue. I'll try to fix this.

Weird, the Windows API i'm using is DwmExtendArea may be improved/changed in newer windows versions. Seems like issue related with the Windows APIs.

**Comment by arshx86** [comment]
Ping.
@ffgapple issue seems to be fixed, I'm on 22H2 and works smoothly.
Please let me know if you are facing with this issue still, I will try to add backward WinAPI compatability to it.
